apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  labels:
    app: webhook-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-pod
  template:
    metadata:
      labels:
        app: webhook-pod
    spec:
      containers:
        - name: webhook-container
          image: shahincsejnu/mutator-webhook:v1.0.13
          ports:
            - containerPort: 8443